-- Supabase/PostgreSQL schema for AIMS.
-- Run this in the Supabase SQL Editor for project yifpferiexemkghcipze.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS staff_accounts (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(32) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('Admin', 'Manager', 'Staff')),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    contact_number VARCHAR(20),
    email VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id INTEGER PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL DEFAULT '',
    user_type VARCHAR(50) NOT NULL DEFAULT 'Student',
    membership_type VARCHAR(100) NOT NULL DEFAULT 'Open Time',
    history_json TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS memberships (
    membership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    membership_type VARCHAR(50),
    discount_rate NUMERIC(5,2),
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memberships_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS promotions (
    promo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_name VARCHAR(100),
    promo_type VARCHAR(100),
    discount_rate NUMERIC(5,2),
    discount_label VARCHAR(100),
    start_date DATE,
    end_date DATE,
    benefits TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS membership_types (
    membership_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(120) NOT NULL,
    duration_label VARCHAR(80) NOT NULL,
    price_label VARCHAR(80) NOT NULL,
    benefits TEXT NOT NULL,
    created_by_staff_id INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_membership_types_staff
        FOREIGN KEY (created_by_staff_id) REFERENCES staff_accounts(staff_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    booking_date DATE,
    start_time TIME,
    end_time TIME,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Cancelled')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking_meta (
    booking_id INTEGER PRIMARY KEY,
    space_type VARCHAR(30) NOT NULL DEFAULT 'Open Space' CHECK (space_type IN ('Board Room', 'Open Space')),
    customer_type VARCHAR(50) NOT NULL DEFAULT 'Guest',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_meta_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Completed')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS session_meta (
    session_id INTEGER PRIMARY KEY,
    space_used VARCHAR(30) NOT NULL DEFAULT 'Open Space' CHECK (space_used IN ('Board Room', 'Open Space')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_meta_session
        FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    session_id INTEGER NULL,
    amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    discount_applied NUMERIC(10,2) NOT NULL DEFAULT 0,
    final_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(50) DEFAULT 'cash',
    status VARCHAR(20) NOT NULL DEFAULT 'paid' CHECK (status IN ('paid', 'pending', 'failed')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_transactions_session
        FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS api_sessions (
    token CHAR(64) PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_api_sessions_staff
        FOREIGN KEY (staff_id) REFERENCES staff_accounts(staff_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS space_pricing (
    pricing_id SMALLINT PRIMARY KEY,
    board_room_hourly_rate NUMERIC(10,2) NOT NULL,
    ordinary_space_hourly_rate NUMERIC(10,2) NOT NULL,
    updated_by_staff_id INTEGER NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_space_pricing_staff
        FOREIGN KEY (updated_by_staff_id) REFERENCES staff_accounts(staff_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS meeting_schedules (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    notes VARCHAR(255) NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    created_by_staff_id INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_meeting_schedules_staff
        FOREIGN KEY (created_by_staff_id) REFERENCES staff_accounts(staff_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_meeting_schedules_start_at
    ON meeting_schedules(start_at);

CREATE INDEX IF NOT EXISTS idx_bookings_date_status
    ON bookings(booking_date, status);

CREATE INDEX IF NOT EXISTS idx_sessions_status_check_in
    ON sessions(status, check_in);

CREATE INDEX IF NOT EXISTS idx_transactions_created_at
    ON transactions(created_at);

CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_accounts_employee_id_lower
    ON staff_accounts(LOWER(employee_id));

CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_accounts_email_lower
    ON staff_accounts(LOWER(email));

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower
    ON users(LOWER(email))
    WHERE email IS NOT NULL;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_profiles_updated_at ON user_profiles;
CREATE TRIGGER trg_user_profiles_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_membership_types_updated_at ON membership_types;
CREATE TRIGGER trg_membership_types_updated_at
BEFORE UPDATE ON membership_types
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_space_pricing_updated_at ON space_pricing;
CREATE TRIGGER trg_space_pricing_updated_at
BEFORE UPDATE ON space_pricing
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_meeting_schedules_updated_at ON meeting_schedules;
CREATE TRIGGER trg_meeting_schedules_updated_at
BEFORE UPDATE ON meeting_schedules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION aims_verify_staff_login(
    input_role TEXT,
    input_identifier TEXT,
    input_password TEXT
)
RETURNS TABLE (
    staff_id INTEGER,
    employee_id VARCHAR,
    full_name VARCHAR,
    email VARCHAR,
    role VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        s.staff_id,
        s.employee_id,
        s.full_name,
        s.email,
        s.role,
        s.status,
        s.created_at
    FROM staff_accounts s
    WHERE LOWER(s.role) = LOWER(input_role)
      AND LOWER(s.status) = 'active'
      AND (
          LOWER(s.employee_id) = LOWER(input_identifier)
          OR LOWER(s.email) = LOWER(input_identifier)
      )
      AND (
          s.password_hash = input_password
          OR extensions.crypt(input_password, REPLACE(s.password_hash, '$2y$', '$2a$'))
              = REPLACE(s.password_hash, '$2y$', '$2a$')
      )
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION aims_create_staff_account(
    input_employee_id TEXT,
    input_full_name TEXT,
    input_email TEXT,
    input_password TEXT,
    input_role TEXT,
    input_status TEXT
)
RETURNS TABLE (
    staff_id INTEGER,
    employee_id VARCHAR,
    full_name VARCHAR,
    email VARCHAR,
    role VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    INSERT INTO staff_accounts (
        employee_id,
        full_name,
        email,
        password_hash,
        role,
        status
    )
    VALUES (
        UPPER(input_employee_id),
        input_full_name,
        LOWER(input_email),
        extensions.crypt(input_password, extensions.gen_salt('bf')),
        input_role,
        input_status
    )
    RETURNING
        staff_accounts.staff_id,
        staff_accounts.employee_id,
        staff_accounts.full_name,
        staff_accounts.email,
        staff_accounts.role,
        staff_accounts.status,
        staff_accounts.created_at;
$$;

CREATE OR REPLACE FUNCTION aims_update_staff_account(
    input_staff_id INTEGER,
    input_employee_id TEXT,
    input_full_name TEXT,
    input_email TEXT,
    input_password TEXT,
    input_role TEXT,
    input_status TEXT
)
RETURNS TABLE (
    staff_id INTEGER,
    employee_id VARCHAR,
    full_name VARCHAR,
    email VARCHAR,
    role VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE staff_accounts
    SET employee_id = UPPER(input_employee_id),
        full_name = input_full_name,
        email = LOWER(input_email),
        password_hash = CASE
            WHEN COALESCE(input_password, '') = '' THEN staff_accounts.password_hash
            ELSE extensions.crypt(input_password, extensions.gen_salt('bf'))
        END,
        role = input_role,
        status = input_status
    WHERE staff_accounts.staff_id = input_staff_id
    RETURNING
        staff_accounts.staff_id,
        staff_accounts.employee_id,
        staff_accounts.full_name,
        staff_accounts.email,
        staff_accounts.role,
        staff_accounts.status,
        staff_accounts.created_at;
$$;

GRANT EXECUTE ON FUNCTION aims_verify_staff_login(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION aims_create_staff_account(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION aims_update_staff_account(INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;

INSERT INTO staff_accounts (employee_id, full_name, email, password_hash, role, status)
VALUES ('ADMIN-001', 'System Administrator', 'admin@afterspace.local', 'admin123', 'Admin', 'Active')
ON CONFLICT (employee_id) DO NOTHING;

INSERT INTO staff_accounts (employee_id, full_name, email, password_hash, role, status)
VALUES ('MGR-001', 'Operations Manager', 'manager@afterspace.local', 'manager123', 'Manager', 'Active')
ON CONFLICT (employee_id) DO NOTHING;

INSERT INTO staff_accounts (employee_id, full_name, email, password_hash, role, status)
VALUES ('STF-001', 'Front Desk Staff', 'staff@afterspace.local', 'staff123', 'Staff', 'Active')
ON CONFLICT (employee_id) DO NOTHING;
